---
- name: Download Prometheus
  get_url:
    url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Create Prometheus service file
  copy:
    dest: /etc/systemd/system/prometheus.service
    content: |
      [Unit]
      Description=Prometheus
      After=network.target

      [Service]
      ExecStart=/usr/local/bin/prometheus-2.43.0.linux-amd64/prometheus --config.file=/usr/local/bin/prometheus-2.43.0.linux-amd64/prometheus.yml
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Start and enable Prometheus service
  systemd:
    name: prometheus
    state: started
    enabled: true
